x-comon:
  schnee-database:
    Postgress-Password: &db-password "schnee-2024/25"

services:
  database:
    container_name: Schnee-DB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: *db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-setup:
    depends_on:
      database:
        condition: service_healthy
    container_name: Schnee-DB-Setup
    image: themodcrafttmc/db-setup:latest
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: *db-password
      DB_NAME: Schnuppitool
      DB_Type: "PostGre"
      SQL_FILE: "sql/init.sql"
    volumes:
      - ./sql/init.sql:/app/sql/init.sql